version: 2

models:
  - name: stg_greenery__addresses
    config:
      materialized: view
    description: A view of all addresses that have been registered at Greenery
    
    columns:
      - name: address_guid
      - name: address
      - name: zipcode
      - name: state
      - name: country


  - name: stg_greenery__events
    config:
      materialized: view
    description: A view of all user created events on the Greenery website (ex. view page, add item to cart, cart checkout, etc.)
    
    columns:
      - name: event_guid
      - name: session_guid
      - name: user_guid
      - name: page_url
      - name: created_at_utc
      - name: event_type
        tests:
          - accepted_values:
              values: ['add_to_cart','checkout','page_view','package_shipped']
      - name: order_guid
      - name: product_guid


  - name: stg_greenery__order_items
    config:
      materialized: view
    description: A view of all items in a given customer order, and the quantity of items per order
    
    columns:
      - name: order_guid
      - name: product_guid
      - name: quantity


  - name: stg_greenery__orders
    config: 
      materialized: view
    description: A view of all customer orders and the metadata associated with those orders (customer, address, shipping status, cost, etc.)
    
    columns: 
      - name: order_guid
      - name: user_guid
      - name: promo_id
      - name: address_guid
      - name: created_at_utc
      - name: order_cost
      - name: shipping_cost
      - name: order_total
      - name: tracking_guid
      - name: shipping_service
      - name: estimated_delivery_at_utc
      - name: delivered_at_utc
      - name: order_status
        tests:
        - accepted_values:
            values: ['preparing','shipped','delivered']
  

  - name: stg_greenery__products
    config: 
      materialized: view
    description: A view of all the products available on the Greenery website, including associated cost and product inventory.
    
    columns: 
      - name: product_guid
      - name: product_name
      - name: product_price
      - name: product_inventory
  

  - name: stg_greenery__promos
    config: 
      materialized: view
    description: A view of all historical promotional codes on the Greenery website (active and inactive promo codes).
    
    columns:
      - name: promo_id
      - name: discount
      - name: promo_status
  

  - name: stg_greenery__users
    config: 
      materialized: view
    description: A view of all users registered with the Greenery website and their associated data (name, address, phone number, etc.).
    
    columns: 
      - name: user_guid
      - name: first_name
      - name: last_name
      - name: email 
      - name: phone_number
      - name: created_at_utc
      - name: updated_at_utc
      - name: address_guid
